AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mys3bucketaryantask2
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: MyS3Bucket
        - Key: Environment
          Value: Production
      LoggingConfiguration:
        DestinationBucketName: mys3bucketaryantask2
        LogFilePrefix: bucket_access_logs/
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter1Day
            Status: Enabled
            Prefix: ''
            ExpirationInDays: 1
          - Id: DeleteAfter2Days
            Status: Enabled
            Prefix: bucket_access_logs/
            ExpirationInDays: 2
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Id: ReplicateToUSWest2
            Status: Enabled
            DeleteMarkerReplication:
              Status: Enabled
            Priority: 1
            Filter:
              Prefix: ''
            Destination:
              Bucket: arn:aws:s3:::replicationbuckettaskkks
              StorageClass: STANDARD
          - Id: ReplicateToAnotherAccount
            Status: Enabled
            DeleteMarkerReplication:
              Status: Enabled
            Priority: 2
            Filter:
              Prefix: ''
            Destination:
              Bucket: arn:aws:s3:::pocfordrago
              StorageClass: STANDARD
          - Id: ReplicateToAnotherAccountWithAnotherRegion
            Status: Enabled
            DeleteMarkerReplication:
              Status: Enabled
            Priority: 3
            Filter:
              Prefix: ''
            Destination:
              Bucket: arn:aws:s3:::athena-glue-poc-test-dev
              StorageClass: STANDARD

  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "s3.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "S3ReplicationPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetReplicationConfiguration"
                  - "s3:ListBucket"
                Resource: arn:aws:s3:::mys3bucketaryantask2
              - Effect: "Allow"
                Action:
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectVersionAcl"
                  - "s3:GetObjectVersionTagging"
                  - "s3:PutObject"
                Resource: arn:aws:s3:::mys3bucketaryantask2/*
